# Generated by Django 5.2.7 on 2025-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='habitentry',
            name='status',
        ),
        migrations.AddField(
            model_name='habitentry',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
